import { describe,expect,test } from 'bun:test'
import { buildOptsFromFlags } from '~/cli/options/option-resolution/build-options-from-flags'

describe('option resolution contracts', () => {

  test('--all-llm expands OpenAI, Anthropic, Grok, GLM, Kimi, Together, and Cerebras to their supported models', () => {
      const opts = buildOptsFromFlags({ 'all-llm': true })

      expect(opts.openaiModels).toEqual(['gpt-5.6-sol', 'gpt-5.6-terra', 'gpt-5.6-luna', 'gpt-5.5', 'gpt-5.4-mini', 'gpt-5.4-nano'])
      expect(opts.openaiModels).not.toContain('gpt-5.6')
      expect(opts.anthropicModels).toEqual(['claude-fable-5', 'claude-opus-4-8', 'claude-sonnet-5', 'claude-sonnet-4-6', 'claude-haiku-4-5', 'claude-opus-5'])
      expect(opts.anthropicModels).not.toContain('claude-mythos-5')
      expect(opts.geminiModels).toEqual(['gemini-3.1-pro-preview', 'gemini-3.7-flash', 'gemini-3.6-flash', 'gemini-3.5-flash', 'gemini-3.5-flash-lite'])
      expect(opts.geminiModels).not.toContain('gemini-3.1-flash-lite')
      expect(opts.geminiModels).not.toContain('gemini-3-flash-preview')
      expect(opts.grokModels).toEqual(['grok-4.3', 'grok-4.5', 'grok-4.6'])
      expect(opts.glmModels).toEqual(['glm-5.1'])
      expect(opts.kimiModels).toEqual(['kimi-k2.6', 'kimi-k3'])
      expect(opts.togetherModels).toEqual(['kimi-k2.6', 'glm-5.1'])
      expect(opts.cerebrasModels).toEqual(['gpt-oss-120b', 'zai-glm-4.7'])
    })

  test('priority OCR model additions are available without changing provider defaults', () => {
      const openaiWriteOpts = buildOptsFromFlags({ openai: 'gpt-5.4-mini' })
      const openaiSolWriteOpts = buildOptsFromFlags({ openai: 'gpt-5.6-sol' })
      const openaiGpt55WriteOpts = buildOptsFromFlags({ openai: 'gpt-5.5' })
      const mistralOcr4Opts = buildOptsFromFlags({ 'mistral-ocr': 'mistral-ocr-4-0' })
      const openaiSolOcrOpts = buildOptsFromFlags({ 'openai-ocr': 'gpt-5.6-sol' })
      const openaiOcrOpts = buildOptsFromFlags({ 'openai-ocr': 'gpt-5.4-nano' })
      const openaiMiniOcrOpts = buildOptsFromFlags({ 'openai-ocr': 'gpt-5.4-mini' })
      const openaiGpt55OcrOpts = buildOptsFromFlags({ 'openai-ocr': 'gpt-5.5' })
      const grokWriteOpts = buildOptsFromFlags({ grok: 'grok-4.3' })
      const grokOcrOpts = buildOptsFromFlags({ 'grok-ocr': 'grok-4.3' })
      const grok420OcrOpts = buildOptsFromFlags({ 'grok-ocr': 'grok-4.20-0309-non-reasoning' })
      const grok45OcrOpts = buildOptsFromFlags({ 'grok-ocr': 'grok-4.5' })
      const grok46OcrOpts = buildOptsFromFlags({ 'grok-ocr': 'grok-4.6' })
      const gemini35OcrOpts = buildOptsFromFlags({ 'gemini-ocr': 'gemini-3.5-flash' })
      const gemini37OcrOpts = buildOptsFromFlags({ 'gemini-ocr': 'gemini-3.7-flash' })
      const writeOpts = buildOptsFromFlags({ anthropic: 'claude-sonnet-4-6' })
      const anthropicFableWriteOpts = buildOptsFromFlags({ anthropic: 'claude-fable-5' })
      const anthropicSonnet5WriteOpts = buildOptsFromFlags({ anthropic: 'claude-sonnet-5' })
      const anthropicFableOcrOpts = buildOptsFromFlags({ 'anthropic-ocr': 'claude-fable-5' })
      const anthropicOpusOcrOpts = buildOptsFromFlags({ 'anthropic-ocr': 'claude-opus-4-8' })
      const anthropicSonnet5OcrOpts = buildOptsFromFlags({ 'anthropic-ocr': 'claude-sonnet-5' })
      const anthropicSonnet46OcrOpts = buildOptsFromFlags({ 'anthropic-ocr': 'claude-sonnet-4-6' })
      const anthropicHaikuOcrOpts = buildOptsFromFlags({ 'anthropic-ocr': 'claude-haiku-4-5' })

      expect(openaiWriteOpts.openaiModels?.[0]).toBe('gpt-5.4-mini')
      expect(openaiSolWriteOpts.openaiModels?.[0]).toBe('gpt-5.6-sol')
      expect(openaiGpt55WriteOpts.openaiModels?.[0]).toBe('gpt-5.5')
      expect(mistralOcr4Opts.mistralOcrModels?.[0]).toBe('mistral-ocr-4-0')
      expect(openaiSolOcrOpts.openaiOcrModels?.[0]).toBe('gpt-5.6-sol')
      expect(openaiOcrOpts.openaiOcrModels?.[0]).toBe('gpt-5.4-nano')
      expect(openaiOcrOpts.openaiOcrModels).toEqual(['gpt-5.4-nano'])
      expect(openaiMiniOcrOpts.openaiOcrModels?.[0]).toBe('gpt-5.4-mini')
      expect(openaiGpt55OcrOpts.openaiOcrModels?.[0]).toBe('gpt-5.5')
      expect(grokWriteOpts.grokModels?.[0]).toBe('grok-4.3')
      expect(grokOcrOpts.grokOcrModels?.[0]).toBe('grok-4.3')
      expect(grokOcrOpts.grokOcrModels).toEqual(['grok-4.3'])
      expect(grok420OcrOpts.grokOcrModels?.[0]).toBe('grok-4.20-0309-non-reasoning')
      expect(grok45OcrOpts.grokOcrModels?.[0]).toBe('grok-4.5')
      expect(grok46OcrOpts.grokOcrModels?.[0]).toBe('grok-4.6')
      expect(gemini35OcrOpts.geminiOcrModels?.[0]).toBe('gemini-3.5-flash')
      expect(gemini37OcrOpts.geminiOcrModels?.[0]).toBe('gemini-3.7-flash')
      expect(writeOpts.anthropicModels?.[0]).toBe('claude-sonnet-4-6')
      expect(anthropicFableWriteOpts.anthropicModels?.[0]).toBe('claude-fable-5')
      expect(anthropicSonnet5WriteOpts.anthropicModels?.[0]).toBe('claude-sonnet-5')
      expect(anthropicFableOcrOpts.anthropicOcrModels?.[0]).toBe('claude-fable-5')
      expect(anthropicOpusOcrOpts.anthropicOcrModels?.[0]).toBe('claude-opus-4-8')
      expect(anthropicOpusOcrOpts.anthropicOcrModels).toEqual(['claude-opus-4-8'])
      expect(anthropicSonnet5OcrOpts.anthropicOcrModels?.[0]).toBe('claude-sonnet-5')
      expect(anthropicSonnet46OcrOpts.anthropicOcrModels?.[0]).toBe('claude-sonnet-4-6')
      expect(anthropicHaikuOcrOpts.anthropicOcrModels?.[0]).toBe('claude-haiku-4-5')
      expect(() => buildOptsFromFlags({ openai: 'gpt-5.6' })).toThrow()
      expect(() => buildOptsFromFlags({ anthropic: 'claude-mythos-5' })).toThrow()
    })
})
