import { describe, expect, test } from 'bun:test'
import { rm, writeFile } from 'node:fs/promises'
import {
  classifyLiveProviderAvailabilityFailure,
  formatCommandFailureDiagnostics,
  getMissingConfiguredEnvVarKeysSync
} from '../../../test-utils/service-test-kit'
import { makeTempDir } from '../../../test-utils/temp-dirs'

describe('classifyLiveProviderAvailabilityFailure', () => {
  test('classifies known live-provider availability failures', () => {
    const cases: Array<{ output: string; expected: string }> = [
      {
        output: '\x1b[31mYou do not have enough credits to run this task.\x1b[0m',
        expected: 'Runway account does not have enough credits to run this task'
      },
      {
        output: 'Failed to run GLM model: {"code":"1113","message":"insufficient balance"}',
        expected: 'GLM account does not have enough balance or an active resource package'
      },
      {
        output: 'GLM Reader request failed (429 Too Many Requests): rate limit exceeded',
        expected: 'GLM Reader is rate limited'
      },
      {
        output: 'glm/glm-ocr: certificate has expired',
        expected: 'GLM provider TLS certificate has expired'
      },
      {
        output: 'Retry Attempt\noperation glm-ocr reason retryable status 429\nCommand failed: glm-ocr failed after 4/4 attempts',
        expected: 'GLM provider remained rate limited after retries'
      },
      {
        output: 'Retry Attempt\noperation glm-llm reason retryable status 429\nFailed to run GLM model: glm-llm failed after 2/2 attempts',
        expected: 'GLM provider remained rate limited after retries'
      },
      {
        output: 'DeepInfra target openai/whisper-large-v3 command timed out after 300000ms',
        expected: 'DeepInfra openai/whisper-large-v3 transcription timed out'
      },
      {
        output: 'Retry Attempt\noperation gemini-image-generate\nreason retryable status 503\nFailed to run Gemini image model gemini-3.1-flash-lite-image: gemini-image-generate failed after 3/3 attempts (max attempts reached, 2100ms elapsed)\nGemini API request failed with status 503: service unavailable',
        expected: 'Gemini image provider is temporarily unavailable or rate limited'
      },
      {
        output: 'gemini/gemini-3.1-flash-lite-image Gemini API request failed with status 429: Resource exhausted',
        expected: 'Gemini image provider is temporarily unavailable or rate limited'
      },
      {
        output: 'BFL image result download failed (504)',
        expected: 'BFL image result download hit a transient provider availability failure'
      },
      {
        output: 'Retry Attempt\noperation bfl-image-result-download\nreason retryable status 504\nflux-2-flex bfl-image-result-download failed after 4/4 attempts (max attempts reached, 4200ms elapsed)',
        expected: 'BFL image result download hit a transient provider availability failure'
      },
      {
        output: 'Retry Attempt\noperation together-stt-create\nreason retryable status 503\ntogether-stt-create failed after 2/2 attempts (max attempts reached, 4200ms elapsed)\nTogether transcription failed (503): Service Unavailable',
        expected: 'Together STT provider remained unavailable after retries'
      },
      {
        output: 'Retry Attempt\noperation together-stt-create\nreason network error\ntogether-stt-create failed after 2/2 attempts (max attempts reached, 4200ms elapsed)\nSocket connection was closed unexpectedly',
        expected: 'Together STT provider remained unavailable after retries'
      },
      {
        output: 'Failed to run image target gemini/gemini-3.1-flash-lite-image: No image content in Gemini response (blockReason=IMAGE_SAFETY)',
        expected: 'Gemini image provider returned a response with no image content (refusal or filtered prompt)'
      },
      {
        output: 'gemini/gemini-3-pro-image No images were generated by Gemini',
        expected: 'Gemini image provider returned a response with no image content (refusal or filtered prompt)'
      },
      {
        output: 'supadata/auto detail: Supadata request failed (429): Limit Exceeded',
        expected: 'Supadata account plan limit is exhausted'
      },
      {
        output: 'Supadata scrape failed (429 Too Many Requests): Limit Exceeded',
        expected: 'Supadata account plan limit is exhausted'
      }
    ]

    for (const { output, expected } of cases) {
      expect(classifyLiveProviderAvailabilityFailure(output)).toBe(expected)
    }
  })

  test('does not classify unrelated failures or the DeepInfra turbo model', () => {
    expect(classifyLiveProviderAvailabilityFailure('GLM validation failed because output was malformed')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('command timed out for openai/whisper-large-v3')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('DeepInfra openai/whisper-large-v3 completed')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('DeepInfra openai/whisper-large-v3-turbo command timed out')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('Gemini image validation failed because output was malformed')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('Failed to run Gemini model: Gemini API request failed with status 503')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('Gemini API request failed with status 400 for gemini-3.1-flash-lite-image: invalid prompt')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('BFL image request failed (400): invalid prompt')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('flux-2-flex bfl-image-result-download failed after 2/4 attempts (non-retryable status 400, 1200ms elapsed)')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('Together validation failed because transcript was empty')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('No image content in Gemini response')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('Supadata request failed (401): Invalid API key')).toBeNull()
    expect(classifyLiveProviderAvailabilityFailure('Limit Exceeded')).toBeNull()
  })
})

describe('getMissingConfiguredEnvVarKeysSync', () => {
  test('uses process env for synchronous service-test availability checks', () => {
    const key = 'SERVICE_KIT_TEST_SYNC_ENV_KEY'
    const previous = process.env[key]
    try {
      delete process.env[key]
      expect(getMissingConfiguredEnvVarKeysSync([key])).toEqual([key])

      process.env[key] = ' configured '
      expect(getMissingConfiguredEnvVarKeysSync([key])).toEqual([])
    } finally {
      if (previous === undefined) {
        delete process.env[key]
      } else {
        process.env[key] = previous
      }
    }
  })

  test('uses .env for synchronous service-test availability checks', async () => {
    const previousCwd = process.cwd()
    const tempDir = await makeTempDir('autoshow-service-env-')
    try {
      process.chdir(tempDir)
      await writeFile('.env', 'SERVICE_KIT_TEST_DOTENV_KEY=dotenv-value\n', 'utf8')
      expect(getMissingConfiguredEnvVarKeysSync(['SERVICE_KIT_TEST_DOTENV_KEY'])).toEqual([])
      expect(getMissingConfiguredEnvVarKeysSync(['SERVICE_KIT_TEST_MISSING_KEY'])).toEqual(['SERVICE_KIT_TEST_MISSING_KEY'])
    } finally {
      process.chdir(previousCwd)
      await rm(tempDir, { recursive: true, force: true })
    }
  })
})

describe('formatCommandFailureDiagnostics', () => {
  test('prints a compact command, stdout tail, and stderr tail', () => {
    const output = formatCommandFailureDiagnostics(
      ['src/cli/create-cli.ts', 'video', 'A serene mountain landscape', '--runway', 'gen4.5'],
      {
        exitCode: 1,
        stdout: ['stdout 1', 'stdout 2', 'stdout 3'].join('\n'),
        stderr: ['stderr 1', 'stderr 2', 'stderr 3'].join('\n')
      },
      2
    )

    expect(output).toContain('Command failed with exit code 1: bun src/cli/create-cli.ts video "A serene mountain landscape" --runway gen4.5')
    expect(output).toContain('--- stdout tail (2 lines) ---\nstdout 2\nstdout 3')
    expect(output).toContain('--- stderr tail (2 lines) ---\nstderr 2\nstderr 3')
    expect(output).not.toContain('stdout 1')
    expect(output).not.toContain('stderr 1')
  })
})
