export type MusicRuntimeOptionKey =
  | 'musicProviderConcurrency'
  | 'musicLocalConcurrency'
  | 'elevenlabsMusicModels'
  | 'elevenlabsMusicModel'
  | 'minimaxMusicModels'
  | 'minimaxMusicModel'
  | 'geminiMusicModels'
  | 'geminiMusicModel'
  | 'musicDuration'
  | 'musicLyricsFile'
  | 'musicInstrumental'
