import { expect, test } from 'bun:test'
import { LUMALABS_MAX_IMAGE_INPUTS } from '~/cli/commands/process-steps/step-5-image/image-generation-services/lumalabs/lumalabs-image-targets'
import { ELEVENLABS_MAX_DURATION_SECONDS, ELEVENLABS_MIN_DURATION_SECONDS } from '~/cli/commands/process-steps/step-7-music/music-services/music-elevenlabs/run-elevenlabs-music-gen'
import { getFlagGroupSection, loadHelp } from './shared'

export const registerMediaCommandHelpCases = (): void => {
  test.concurrent('tts help exposes hosted TTS provider flags', async () => {
    const result = await loadHelp(['tts', '--help'])

    expect(result.exitCode).toBe(0)
    expect(getFlagGroupSection(result.stdout, 'Provider Selection')).toContain('--provider')
    expect(getFlagGroupSection(result.stdout, 'Provider Selection')).toContain('--provider-concurrency')
    expect(getFlagGroupSection(result.stdout, 'Text to Speech')).toContain('--tts-voice')
    expect(getFlagGroupSection(result.stdout, 'Text to Speech')).toContain('--tts-chunk-concurrency')
    expect(getFlagGroupSection(result.stdout, 'Batch Processing')).toContain('--batch-concurrency')
    expect(getFlagGroupSection(result.stdout, 'MiniMax TTS')).toContain('--minimax-tts-volume')
    expect(result.stdout).not.toContain('Deepgram TTS')
    expect(result.stdout).not.toContain('Groq TTS')
    expect(result.stdout).not.toContain('Gemini TTS')
    expect(result.stdout).not.toContain('Replicate TTS')
    expect(result.stdout).not.toContain('fal TTS')
    expect(result.stdout).not.toContain('Speechify TTS')
    expect(result.stdout).not.toContain('Hume TTS')
    expect(getFlagGroupSection(result.stdout, 'Multi-Speaker / Dialogue')).toContain('--tts-dialogue-format')
    expect(getFlagGroupSection(result.stdout, 'ElevenLabs TTS')).toContain('--elevenlabs-tts-stability')
    expect(getFlagGroupSection(result.stdout, 'Pricing')).toContain('--price')
    expect(getFlagGroupSection(result.stdout, 'Pricing')).toContain('--max-model-cents')
    expect(result.stdout).toContain('--provider')
    expect(result.stdout).toContain('--all-providers')
    expect(result.stdout).not.toContain('--all-local')
    expect(result.stdout).toContain('--provider-concurrency')
    expect(result.stdout).not.toContain('--local-concurrency')
    expect(result.stdout).toContain('--tts-voice')
    expect(result.stdout).toContain('--tts-speed')
    expect(result.stdout).toContain('--tts-language')
    expect(result.stdout).toContain('--tts-ref-audio')
    expect(result.stdout).not.toContain('--tts-voice-name')
    expect(result.stdout).not.toContain('--tts-consent-audio')
    expect(result.stdout).not.toContain('--tts-consent-language')
    expect(result.stdout).not.toContain('--tts-consent-name')
    expect(result.stdout).toContain('--allow-ambiguous-redispatch')
    expect(result.stdout).not.toContain('--tts-allow-ambiguous-redispatch')
    expect(result.stdout).toContain('--tts-text-normalization')
    expect(result.stdout).toContain('--tts-instructions')
    expect(result.stdout).not.toContain('--tts-output-format')
    expect(result.stdout).toContain('--tts-chunk-concurrency')
    expect(result.stdout).toContain('Grok-only uses 50')
    expect(result.stdout).toContain('--batch-concurrency')
    expect(result.stdout).not.toContain('--batch-limit')
    expect(result.stdout).not.toContain('--batch-all')
    expect(result.stdout).not.toContain('--grok-tts  ')
    expect(result.stdout).not.toContain('--grok-tts-voice')
    expect(result.stdout).not.toContain('--grok-tts-language')
    expect(result.stdout).not.toContain('--grok-tts-text-normalization')
    expect(result.stdout).not.toContain('--mistral-tts  ')
    expect(result.stdout).not.toContain('--mistral-tts-voice')
    expect(result.stdout).not.toContain('--mistral-tts-ref-audio')
    expect(result.stdout).not.toContain('--mistral-tts-voice-name')
    expect(result.stdout).not.toContain('--deepgram-tts-encoding')
    expect(result.stdout).not.toContain('--deepgram-tts-container')
    expect(result.stdout).not.toContain('--deepgram-tts-bit-rate')
    expect(result.stdout).not.toContain('--deepgram-tts-sample-rate')
    expect(result.stdout).not.toContain('--deepgram-tts-speed')
    expect(result.stdout).not.toContain('--minimax-tts-voice')
    expect(result.stdout).not.toContain('--minimax-tts-ref-audio')
    expect(result.stdout).not.toContain('--minimax-tts-prompt-audio')
    expect(result.stdout).not.toContain('--minimax-tts-prompt-text')
    expect(result.stdout).not.toContain('--minimax-tts-clone-noise-reduction')
    expect(result.stdout).not.toContain('--minimax-tts-clone-volume-normalization')
    expect(result.stdout).not.toContain('--minimax-tts-language-boost')
    expect(result.stdout).not.toContain('--minimax-tts-speed')
    expect(result.stdout).toContain('--minimax-tts-volume')
    expect(result.stdout).toContain('--minimax-tts-pitch')
    expect(result.stdout).toContain('--minimax-tts-emotion')
    expect(result.stdout).not.toContain('--minimax-tts-english-normalization')
    expect(result.stdout).toContain('--minimax-tts-pronunciation')
    expect(result.stdout).not.toContain('--openai-tts-instructions')
    expect(result.stdout).not.toContain('--openai-tts-speed')
    expect(result.stdout).not.toContain('--openai-tts-ref-audio')
    expect(result.stdout).not.toContain('--openai-tts-consent-id')
    expect(result.stdout).not.toContain('--openai-tts-consent-audio')
    expect(result.stdout).not.toContain('--openai-tts-consent-language')
    expect(result.stdout).not.toContain('--openai-tts-consent-name')
    expect(result.stdout).not.toContain('--openai-tts-voice-name')
    expect(result.stdout).not.toContain('--runway-tts')
    expect(result.stdout).not.toContain('--runway-tts-voice')
    expect(result.stdout).not.toContain('--speechify-tts  ')
    expect(result.stdout).not.toContain('--speechify-voice')
    expect(result.stdout).not.toContain('--speechify-tts-audio-format')
    expect(result.stdout).not.toContain('--speechify-tts-language')
    expect(result.stdout).not.toContain('--speechify-tts-ref-audio')
    expect(result.stdout).not.toContain('--speechify-tts-voice-name')
    expect(result.stdout).not.toContain('--speechify-tts-consent-name')
    expect(result.stdout).not.toContain('--speechify-tts-consent-email')
    expect(result.stdout).not.toContain('--speechify-tts-voice-locale')
    expect(result.stdout).not.toContain('--speechify-tts-voice-gender')
    expect(result.stdout).not.toContain('--hume-tts  ')
    expect(result.stdout).not.toContain('--hume-tts-voice-provider')
    expect(result.stdout).not.toContain('--cartesia-tts  ')
    expect(result.stdout).not.toContain('--cartesia-tts-voice')
    expect(result.stdout).not.toContain('--cartesia-tts-language')
    expect(result.stdout).not.toContain('--elevenlabs-tts-output-format')
    expect(result.stdout).not.toContain('--elevenlabs-tts-language-code')
    expect(result.stdout).not.toContain('--elevenlabs-tts-clone-remove-background-noise')
    expect(result.stdout).toContain('--elevenlabs-tts-stability')
    expect(result.stdout).toContain('--elevenlabs-tts-similarity-boost')
    expect(result.stdout).toContain('--elevenlabs-tts-style')
    expect(result.stdout).toContain('--elevenlabs-tts-use-speaker-boost')
    expect(result.stdout).not.toContain('--elevenlabs-tts-speed')
    expect(result.stdout).toContain('--elevenlabs-tts-seed')
    expect(result.stdout).not.toContain('--elevenlabs-tts-text-normalization')
    expect(result.stdout).toContain('--elevenlabs-tts-pronunciation-dictionary-locator')
    expect(result.stdout).not.toContain('--elevenlabs-tts-optimize-streaming-latency')
  })

  test.concurrent('music help includes hosted generation and lyric-video flags', async () => {
    const result = await loadHelp(['music', '--help'])

    expect(result.exitCode).toBe(0)
    expect(getFlagGroupSection(result.stdout, 'Provider Selection')).toContain('--provider')
    expect(getFlagGroupSection(result.stdout, 'Hosted Music')).toContain('--duration')
    expect(getFlagGroupSection(result.stdout, 'Hosted Music')).toContain('--lyrics-file')
    expect(getFlagGroupSection(result.stdout, 'Pricing')).toContain('--price')
    expect(getFlagGroupSection(result.stdout, 'Pricing')).toContain('--max-model-cents')
    expect(getFlagGroupSection(result.stdout, 'Lyric Video')).toContain('--audio')
    expect(getFlagGroupSection(result.stdout, 'Lyric Video')).toContain('--captions')
    expect(result.stdout).toContain('--provider')
    expect(result.stdout).toContain('--all-providers')
    expect(result.stdout).not.toContain('--all-local')
    expect(result.stdout).not.toContain('--elevenlabs-music')
    expect(result.stdout).not.toContain('--minimax-music')
    expect(result.stdout).not.toContain('--gemini-music')
    expect(result.stdout).toContain('--provider-concurrency')
    expect(result.stdout).not.toContain('--local-concurrency')
    expect(result.stdout).toContain('--duration')
    expect(result.stdout).toContain('--lyrics-file')
    expect(result.stdout).toContain('--instrumental')
    expect(result.stdout).not.toContain('--music-duration')
    expect(result.stdout).not.toContain('--music-lyrics-file')
    expect(result.stdout).toContain('--price')
    expect(result.stdout).toContain('--audio')
    expect(result.stdout).toContain('--captions')
    expect(result.stdout).toContain('--batch')
    expect(result.stdout).toContain('--model')
    expect(result.stdout).toContain('--font')
    expect(result.stdout).not.toContain('--input-dir')
    expect(result.stdout).not.toContain('--keep-tmp')
    expect(result.stdout).not.toContain('--openai')
    expect(result.stdout).not.toContain('--prompt')
    expect(result.stdout).not.toContain('--prompt-file')
    expect(result.stdout).not.toContain('--track-list')
  })

  test.concurrent('image and video help expose generic provider selection plus their own option groups', async () => {
    const imageResult = await loadHelp(['image', '--help'])
    const videoResult = await loadHelp(['video', '--help'])

    expect(imageResult.exitCode).toBe(0)
    expect(videoResult.exitCode).toBe(0)
    expect(getFlagGroupSection(imageResult.stdout, 'Provider Selection')).toContain('--provider')
    expect(getFlagGroupSection(imageResult.stdout, 'Image Options')).toContain('--aspect-ratio')
    expect(getFlagGroupSection(imageResult.stdout, 'Image Inputs')).toContain('--input')
    expect(getFlagGroupSection(imageResult.stdout, 'Provider-Specific Image Options')).toContain('--compression')
    expect(getFlagGroupSection(imageResult.stdout, 'Pricing')).toContain('--price')
    expect(getFlagGroupSection(imageResult.stdout, 'Pricing')).toContain('--max-model-cents')
    expect(getFlagGroupSection(videoResult.stdout, 'Provider Selection')).toContain('--provider')
    expect(getFlagGroupSection(videoResult.stdout, 'Video Options')).toContain('--mode')
    expect(getFlagGroupSection(videoResult.stdout, 'Video Options')).toContain('--generate-audio')
    expect(getFlagGroupSection(videoResult.stdout, 'Video Inputs')).toContain('--input-image')
    expect(getFlagGroupSection(videoResult.stdout, 'Video Inputs')).toContain('--reference-video')
    expect(getFlagGroupSection(videoResult.stdout, 'Video Inputs')).toContain('--reference-audio')
    expect(getFlagGroupSection(videoResult.stdout, 'Replicate Video')).toContain('--replicate-video-seed')
    expect(videoResult.stdout).not.toContain('fal.ai Video')
    expect(getFlagGroupSection(videoResult.stdout, 'Pricing')).toContain('--price')
    expect(getFlagGroupSection(videoResult.stdout, 'Pricing')).toContain('--max-model-cents')
    expect(imageResult.stdout).toContain('gpt-image-2')
    expect(imageResult.stdout).toContain('replicate')
    expect(imageResult.stdout).toContain('wan-video/wan-2.7-image')
    expect(videoResult.stdout).toContain('ltx')
    expect(videoResult.stdout).toContain('ltx-2-3-fast')
    expect(videoResult.stdout).not.toContain('wan-video/wan-2.7-t2v')
    expect(imageResult.stdout).toContain('--provider-concurrency')
    expect(imageResult.stdout).not.toContain('--local-concurrency')
    expect(imageResult.stdout).toContain('--provider')
    expect(imageResult.stdout).toContain('--aspect-ratio')
    expect(imageResult.stdout).toContain('--size')
    expect(imageResult.stdout).toContain('--quality')
    expect(imageResult.stdout).toContain('--format')
    expect(imageResult.stdout).toContain('--count')
    expect(imageResult.stdout).not.toContain('--image-provider-concurrency')
    expect(imageResult.stdout).not.toContain('--image-size')
    expect(imageResult.stdout).not.toContain('--minimax')
    expect(imageResult.stdout).not.toContain('--runway')
    expect(imageResult.stdout).not.toContain('--gemini-person-generation')
    expect(imageResult.stdout).not.toContain('imagen-4.0')
    expect(imageResult.stdout).not.toContain('--glm')
    expect(imageResult.stdout).not.toContain('--bfl-image')
    expect(imageResult.stdout).not.toContain('--replicate-image')
    expect(videoResult.stdout).toContain('--provider-concurrency')
    expect(videoResult.stdout).not.toContain('--local-concurrency')
    expect(videoResult.stdout).toContain('--mode')
    expect(videoResult.stdout).toContain('--input-image')
    expect(videoResult.stdout).toContain('--last-frame')
    expect(videoResult.stdout).toContain('--reference-image')
    expect(videoResult.stdout).toContain('--input-video')
    expect(videoResult.stdout).not.toContain('--size')
    expect(videoResult.stdout).not.toContain('--video-size')
    expect(videoResult.stdout).not.toContain('--video-mode')
    expect(videoResult.stdout).not.toContain('--video-input-image')
    expect(videoResult.stdout).not.toContain('--video-resolution')
    expect(videoResult.stdout).not.toContain('--video-aspect-ratio')
    expect(videoResult.stdout).toContain('Luma Labs')
    expect(videoResult.stdout).toContain('540p|720p|1080p')
    expect(videoResult.stdout).toContain('21:9|9:21|adaptive')
    expect(videoResult.stdout).not.toContain('--grok-video-storage-filename')
    expect(videoResult.stdout).not.toContain('--grok-video-storage-expires-after')
  })

  test.concurrent('Luma, ratio, and music duration descriptions match supported behavior', async () => {
    const image = await loadHelp(['image', '--help'])
    const music = await loadHelp(['music', '--help'])

    expect(image.stdout).toContain('Replicate Seedream also supports match_input_image')
    expect(image.stdout).not.toContain('Replicate Seedream also supports adaptive')
    expect(image.stdout).toContain(`Luma Labs supports up to ${LUMALABS_MAX_IMAGE_INPUTS}`)
    expect(music.stdout).toContain(`ElevenLabs configurable from ${ELEVENLABS_MIN_DURATION_SECONDS}-${ELEVENLABS_MAX_DURATION_SECONDS}`)
    expect(music.stdout).not.toContain('MiniMax currently ignores this flag')
    expect(music.stdout).not.toContain('Gemini Lyria Clip is fixed')
    expect(music.stdout).toContain('Gemini Lyria Pro uses the requested duration')
    expect(image.stdout).toContain('(default: 1)')
  })

  test.concurrent('--replicate-video-multi-prompt description dynamically adapts to video command surface', async () => {
    const video = await loadHelp(['video', '--help'])
    const write = await loadHelp(['write', '--help'])

    expect(video.stdout).toContain('durations sum to --duration)')
    expect(video.stdout).not.toContain('durations sum to --video-duration)')

    expect(write.stdout).not.toContain('--replicate-video-multi-prompt')
  })

}
