import { expect, test } from 'bun:test'
import { FLAG_TO_CONFIG_PATH } from '~/cli/commands/setup-and-utilities/config-command/config-merge'
import {
  getCommandFlagsSection,
  getFlagGroupSection,
  loadHelp,
  persistedVideoInputFlags
} from './shared'

export const registerPipelineCommandHelpCases = (): void => {
  test.concurrent('metadata help groups document, output, article, and batch flags', async () => {
    const result = await loadHelp(['metadata', '--help'])

    expect(result.exitCode).toBe(0)
    expect(getFlagGroupSection(result.stdout, 'Document Options')).toContain('--password')
    expect(getFlagGroupSection(result.stdout, 'Metadata Output')).toContain('--markdown')
    expect(getFlagGroupSection(result.stdout, 'Metadata Output')).toContain('--save')
    expect(getFlagGroupSection(result.stdout, 'Article Extraction')).toContain('--url-provider')
    expect(getFlagGroupSection(result.stdout, 'Batch Processing')).toContain('--batch-limit')
  })

  test.concurrent('extract help exposes shared batch and all-provider flags', async () => {
    const result = await loadHelp(['extract', '--help'])

    expect(result.exitCode).toBe(0)
    const providerSection = getFlagGroupSection(result.stdout, 'Provider Selection')
    const transcriptionSection = getFlagGroupSection(result.stdout, 'Transcription / STT')
    const documentSection = getFlagGroupSection(result.stdout, 'OCR / Document Extraction')
    const articleSection = getFlagGroupSection(result.stdout, 'Article Extraction')
    const batchSection = getFlagGroupSection(result.stdout, 'Batch Processing')
    const transcriptVideoSection = getFlagGroupSection(result.stdout, 'Transcript Video')
    const pricingSection = getFlagGroupSection(result.stdout, 'Pricing')

    expect(providerSection).toContain('--provider')
    expect(providerSection).not.toContain('rev[=')
    expect(providerSection).not.toContain('replicate[=')
    expect(providerSection).not.toContain('fal[=')
    expect(result.stdout).not.toContain('datalab-to/ocr')
    expect(result.stdout).not.toContain('fal-ai/got-ocr')
    expect(result.stdout).not.toContain('fal-ai/florence-2-large/ocr')
    expect(providerSection).toContain('--all-providers')
    expect(providerSection).toContain('--all-local')
    expect(providerSection).toContain('--provider-concurrency')
    expect(providerSection).toContain('--local-concurrency')
    expect(transcriptionSection).toContain('--stt-scrapecreators-lang')
    expect(transcriptionSection).not.toContain('--refresh-cache')
    expect(transcriptionSection).not.toContain('--no-cache')
    expect(documentSection).toContain('--format')
    expect(documentSection).toContain('--primary-ocr')
    expect(documentSection).toContain('--ocr-concurrency')
    expect(documentSection).toContain('--ocr-provider-mode')
    expect(documentSection).toContain('fanout|pool')
    expect(documentSection).toContain('Local OCR defaults to 10')
    expect(documentSection).toContain('hosted OCR defaults to auto')
    expect(documentSection).toContain('--chapters')
    expect(documentSection).toContain('--no-chapters')
    expect(articleSection).toContain('--url-provider-concurrency')
    expect(articleSection).toContain('--url-request-timeout-ms')
    expect(articleSection).toContain('--url-request-attempts')
    expect(providerSection).not.toContain('--url-provider')
    expect(batchSection).toContain('--batch-limit')
    expect(transcriptVideoSection).toContain('--transcript-video')
    expect(transcriptVideoSection).toContain('--transcript-result')
    expect(transcriptVideoSection).toContain('--transcript-text')
    expect(pricingSection).toContain('--price')
    expect(pricingSection).toContain('--max-model-cents')
    expect(result.stdout).toContain('--batch-limit')
    expect(result.stdout).not.toContain('--batch-all')
    expect(result.stdout).toContain('--batch-concurrency')
    expect(result.stdout).toContain('--provider')
    expect(result.stdout).toContain('--all-providers')
    expect(result.stdout).toContain('--all-local')
    expect(result.stdout).not.toContain('--all-stt')
    expect(result.stdout).not.toContain('--all-ocr')
    expect(result.stdout).not.toContain('--all-url')
    expect(result.stdout).not.toContain('--grok-stt')
    expect(result.stdout).not.toContain('--glm-ocr')
    expect(result.stdout).toContain('--stt-scrapecreators-lang')
    expect(result.stdout).not.toContain('--refresh-cache')
    expect(result.stdout).not.toContain('--no-cache')
    expect(result.stdout).toContain('--provider-concurrency')
    expect(result.stdout).toContain('--local-concurrency')
    expect(result.stdout).not.toContain('--ocr-provider-concurrency')
    expect(result.stdout).toContain('--url-provider-concurrency')
    expect(result.stdout).toContain('--url-request-timeout-ms')
    expect(result.stdout).toContain('--url-request-attempts')
    expect(result.stdout).toContain('--stt-preflight-concurrency')
    expect(result.stdout).toContain('--transcript-video')
    expect(result.stdout).toContain('--transcript-result')
    expect(result.stdout).toContain('--transcript-text')
  })

  test.concurrent('download help exposes media preservation flags', async () => {
    const result = await loadHelp(['download', '--help'])

    expect(result.exitCode).toBe(0)
    expect(getFlagGroupSection(result.stdout, 'Document Options')).toContain('--password')
    const mediaSection = getFlagGroupSection(result.stdout, 'Media Download Options')
    expect(mediaSection).toContain('--keep-original-media')
    expect(mediaSection).toContain('--best-quality')
    expect(mediaSection).toContain('--flat-batch')
    expect(getFlagGroupSection(result.stdout, 'Article Extraction')).toContain('--url-provider')
    expect(getFlagGroupSection(result.stdout, 'Batch Processing')).toContain('--batch-limit')
    expect(result.stdout).toContain('--keep-original-media')
    expect(result.stdout).toContain('--best-quality')
    expect(result.stdout).toContain('--flat-batch')
  })


  test.concurrent('write and config help expose shared selectors and concurrency flags', async () => {
    const writeResult = await loadHelp(['write', '--help'])
    const configResult = await loadHelp(['config', '--help'])

    expect(writeResult.exitCode).toBe(0)
    expect(configResult.exitCode).toBe(0)
    const pipelineSection = getFlagGroupSection(writeResult.stdout, 'Pipeline Selection')
    expect(pipelineSection).toContain('--provider-concurrency')
    expect(pipelineSection).toContain('--concurrency-mode')
    expect(pipelineSection).toContain('--all-providers')
    expect(pipelineSection).toContain('--llm')
    expect(pipelineSection).not.toContain('--local-concurrency')
    expect(pipelineSection).not.toContain('--all-local')
    expect(getFlagGroupSection(writeResult.stdout, 'Batch Processing')).toContain('--batch-limit')
    expect(getFlagGroupSection(writeResult.stdout, 'Pricing')).toContain('--max-model-cents')
    expect(getFlagGroupSection(configResult.stdout, 'Concurrency')).toContain('--provider-concurrency')
    expect(getFlagGroupSection(configResult.stdout, 'Concurrency')).toContain('--local-concurrency')
    expect(getFlagGroupSection(configResult.stdout, 'Concurrency')).toContain('--concurrency-mode')
    expect(getFlagGroupSection(configResult.stdout, 'Batch / Download')).toContain('--batch-concurrency')
    expect(getFlagGroupSection(configResult.stdout, 'Pricing')).not.toContain('--provider-concurrency')
    expect(getFlagGroupSection(configResult.stdout, 'Pricing')).not.toContain('--local-concurrency')
    expect(writeResult.stdout).not.toContain('\n  Transcription / STT\n')
    expect(writeResult.stdout).not.toContain('\n  OCR / Document Extraction\n')
    expect(writeResult.stdout).not.toContain('\n  Article Extraction\n')
    expect(getFlagGroupSection(writeResult.stdout, 'Writing')).toContain('--prompt')
    expect(writeResult.stdout).not.toContain('\n  Text to Speech\n')
    expect(writeResult.stdout).not.toContain('\n  Image Options\n')
    expect(writeResult.stdout).not.toContain('\n  Video Options\n')
    expect(writeResult.stdout).not.toContain('\n  Hosted Music\n')
    expect(getFlagGroupSection(configResult.stdout, 'Transcription / STT')).toContain('--stt')
    expect(getFlagGroupSection(configResult.stdout, 'OCR / Document Extraction')).toContain('--ocr')
    expect(getFlagGroupSection(configResult.stdout, 'Writing')).toContain('--llm')
    expect(getFlagGroupSection(configResult.stdout, 'Text to Speech')).toContain('--tts')
    expect(getFlagGroupSection(configResult.stdout, 'Image Options')).toContain('--image')
    expect(getFlagGroupSection(configResult.stdout, 'Video Options')).toContain('--video')
    expect(getFlagGroupSection(configResult.stdout, 'Hosted Music')).toContain('--music')

    const writingStart = writeResult.stdout.indexOf('\n  Writing\n')
    expect(writingStart).toBeGreaterThanOrEqual(0)
    const globalFlagsStart = writeResult.stdout.indexOf('\nGlobal Flags\n', writingStart)
    expect(globalFlagsStart).toBeGreaterThan(writingStart)
    const afterWritingBeforeGlobal = writeResult.stdout.slice(writingStart, globalFlagsStart)
    expect(afterWritingBeforeGlobal).not.toContain('\n    --provider-concurrency')
    expect(afterWritingBeforeGlobal).not.toContain('\n    --local-concurrency')
    expect(afterWritingBeforeGlobal).not.toContain('\n    --all-providers')
    expect(afterWritingBeforeGlobal).not.toContain('\n    --all-local')
    expect(writeResult.stdout).toContain('--provider-concurrency')
    expect(writeResult.stdout).not.toContain('--local-concurrency')
    expect(writeResult.stdout).not.toContain('--stt')
    expect(writeResult.stdout).not.toContain('--ocr')
    expect(writeResult.stdout).toContain('--llm')
    expect(writeResult.stdout).toContain('grok=grok-4.5')
    expect(writeResult.stdout).not.toContain('--tts')
    expect(writeResult.stdout).not.toContain('--image')
    expect(writeResult.stdout).not.toContain('--video')
    expect(writeResult.stdout).not.toContain('--music')
    expect(writeResult.stdout).toContain('--all-providers')
    expect(writeResult.stdout).not.toContain('--all-local')
    expect(writeResult.stdout).not.toContain('--llm-provider-concurrency')
    expect(writeResult.stdout).not.toContain('--mistral-stt')
    expect(configResult.stdout).toContain('--provider-concurrency')
    expect(configResult.stdout).toContain('--local-concurrency')
    expect(configResult.stdout).toContain('--stt')
    expect(configResult.stdout).toContain('--ocr')
    expect(configResult.stdout).toContain('--llm')
    expect(configResult.stdout).toContain('--tts')
    expect(configResult.stdout).toContain('gemini|openai|grok|bfl|replicate')
    expect(configResult.stdout).toContain('--tts-chunk-concurrency')
    expect(writeResult.stdout).not.toContain('Grok-only uses 50')
    expect(configResult.stdout).toContain('Grok-only uses 50')
    expect(configResult.stdout).toContain('--ocr-concurrency')
    expect(configResult.stdout).toContain('--ocr-provider-mode')
    expect(configResult.stdout).not.toContain('--music-instrumental')
    expect(configResult.stdout).not.toContain('--instrumental')
    expect(configResult.stdout).not.toContain('--music-lyrics-file')
    expect(configResult.stdout).not.toContain('--prompt-md')
    expect(configResult.stdout).not.toContain('--allow-ambiguous-redispatch')
    expect(configResult.stdout).not.toContain('--tts-allow-ambiguous-redispatch')
    expect(configResult.stdout).not.toContain('--llm-provider-concurrency')
    expect(configResult.stdout).not.toContain('--mistral-stt')
    expect(configResult.stdout).not.toContain('openai=gpt-5.4 --stt')
  })


  test.concurrent('resume help exposes unified multi-target provider selector', async () => {
    const result = await loadHelp(['resume', '--help'])

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain('--provider')
    expect(getFlagGroupSection(result.stdout, 'Provider Selection')).not.toContain('--url-provider')
    expect(result.stdout).toContain('--all-providers')
    expect(result.stdout).toContain('--all-local')
    expect(result.stdout).toContain('--provider-concurrency')
    expect(result.stdout).toContain('--local-concurrency')
    expect(result.stdout).toContain('--ocr-concurrency')
    expect(getFlagGroupSection(result.stdout, 'Batch Processing')).toContain('--batch-concurrency')
    expect(getFlagGroupSection(result.stdout, 'Transcription / STT')).toContain('--youtube-captions')
    expect(getFlagGroupSection(result.stdout, 'OCR / Document Extraction')).not.toContain('--batch-concurrency')
    expect(getFlagGroupSection(result.stdout, 'Text to Speech')).toContain('--tts-voice')
    expect(getFlagGroupSection(result.stdout, 'Image Options')).toContain('--size')
    expect(getFlagGroupSection(result.stdout, 'Video Options')).toContain('--aspect-ratio')
    expect(getFlagGroupSection(result.stdout, 'Hosted Music')).toContain('--duration')
    expect(result.stdout).toContain('STT:')
    expect(result.stdout).toContain('OCR:')
    expect(result.stdout).toContain('TTS:')
    expect(result.stdout).toContain('image:')
    expect(result.stdout).toContain('video:')
    expect(result.stdout).toContain('music:')
    expect(result.stdout).toContain('whisper')
    expect(result.stdout).toContain('tesseract')
    expect(result.stdout).toContain('bfl')
    expect(result.stdout).not.toContain('recraft')
    expect(result.stdout).not.toContain('rev[=')
    expect(result.stdout).toContain('replicate')
    expect(result.stdout).not.toContain('runway')
    expect(result.stdout).toContain('ltx')
  })


  test.concurrent('config help shows --max-cents and omits runtime-only --price', async () => {
    const result = await loadHelp(['config', '--help'])

    expect(result.exitCode).toBe(0)
    const pricing = getFlagGroupSection(result.stdout, 'Pricing')
    expect(pricing).toContain('--max-cents')
    expect(pricing).not.toContain('--price')
    expect(pricing).not.toContain('--max-model-cents')
    expect(getCommandFlagsSection(result.stdout)).not.toContain('--price')
    expect(getCommandFlagsSection(result.stdout)).not.toContain('--max-model-cents')
  })

  test.concurrent('config, resume, and write help omit the empty prompt parser default', async () => {
    for (const command of ['config', 'resume', 'write'] as const) {
      const result = await loadHelp([command, '--help'])
      expect(result.exitCode).toBe(0)
      expect(result.stdout).toContain('(default: "default")')
      expect(result.stdout).not.toContain('[default: []]')
    }
  })


  test.concurrent('config examples use the canonical bun autoshow prefix', async () => {
    const result = await loadHelp(['config', '--help'])

    expect(result.exitCode).toBe(0)
    expect(result.stdout).toContain('bun autoshow config --show')
    expect(result.stdout).toContain('bun autoshow config --llm openai=gpt-5.4-mini --stt whisper=base')
    expect(result.stdout).toContain('bun autoshow config --reset')
    expect(result.stdout).not.toContain('bun as config')
  })


  test.concurrent('config help omits command-scoped video input flags while JSON mappings stay namespaced', async () => {
    const result = await loadHelp(['config', '--help'])

    expect(result.exitCode).toBe(0)
    for (const flag of persistedVideoInputFlags) {
      expect(FLAG_TO_CONFIG_PATH[flag]).toBeUndefined()
      expect(getCommandFlagsSection(result.stdout)).not.toContain(`--${flag}`)
    }
  })
}
