import { mkdir } from 'node:fs/promises'
import { basename } from 'node:path'
import type { GeminiImageModel, Step5Metadata } from '~/types'
import { logGenCompleted, logGenStatus } from '~/cli/commands/process-steps/generation-command-utils'
import { requireApiKey } from '~/utils/validate/env-utils'
import { geminiGenerateContent } from '~/utils/gemini/gemini-rest'
import { withRetry } from '~/utils/retries'
import { classifyGeminiRetry } from '~/cli/commands/process-steps/step-3-write/write-services/write-gemini/gemini-utils'
import { imageReferenceToInlineDataPart } from '../../image-utils/image-inputs'
import { getProviderReturnedModel } from '../../image-utils/image-output'
import { InfraError } from '~/utils/error-handler'

export const runGeminiImageGen = async (
  prompt: string,
  outputDir: string,
  options: {
    model: GeminiImageModel
    mode?: 'generation' | 'edit' | undefined
    inputs?: string[] | undefined
    aspectRatio?: string | undefined
    imageSize?: string | undefined
    responseMode?: 'image' | 'text-image' | undefined
    searchGrounding?: boolean | undefined
  }
): Promise<{ imagePaths: string[], metadata: Step5Metadata }> => {
  const apiKey = requireApiKey('GEMINI_API_KEY', 'image:gemini')

  const startTime = Date.now()
  const imagePaths: string[] = []
  const mode = options.mode ?? 'generation'
  let providerReturnedModel: string | undefined
  let groundingMetadata: unknown

  await mkdir(outputDir, { recursive: true })

  logGenStatus('image', 'gemini', options.model, 'started', mode === 'edit' ? 'native image edit' : 'native image')
  const inputParts = await Promise.all((options.inputs ?? []).map(imageReferenceToInlineDataPart))
  const responseModalities = options.responseMode === 'text-image' ? ['TEXT', 'IMAGE'] : ['IMAGE']

  const response = await withRetry(
    {
      retryClass: 'runtime_http_create_conservative',
      operationName: 'gemini-image-generate',
      policy: { maxAttempts: 3 }
    },
    async (signal) => await geminiGenerateContent(apiKey, {
      model: options.model,
      contents: [{ text: prompt }, ...inputParts],
      generationConfig: {
        responseModalities,
        ...(options.aspectRatio || options.imageSize ? {
          imageConfig: {
            ...(options.aspectRatio ? { aspectRatio: options.aspectRatio } : {}),
            ...(options.imageSize ? { imageSize: options.imageSize } : {})
          }
        } : {})
      },
      ...(options.searchGrounding ? { tools: [{ googleSearch: {} }] } : {}),
      ...(signal ? { abortSignal: signal } : {})
    }),
    classifyGeminiRetry
  )
  providerReturnedModel = getProviderReturnedModel(options.model, response)
  groundingMetadata = response.candidates?.find((candidate) => candidate.groundingMetadata !== undefined)?.groundingMetadata

  const candidates = response.candidates ?? []
  if (candidates.length === 0 || !candidates[0]?.content?.parts) {
    throw InfraError('No image content in Gemini response', { stage: 'image:gemini' })
  }

  let imageIndex = 0
  for (const part of candidates[0].content.parts) {
    if (part.inlineData && part.thought !== true) {
      const imageData = part.inlineData.data
      if (!imageData) continue
      const outputPath = imageIndex === 0
        ? `${outputDir}/generated-image.png`
        : `${outputDir}/generated-image-${imageIndex + 1}.png`
      await Bun.write(outputPath, Buffer.from(imageData, 'base64'))
      imagePaths.push(outputPath)
      imageIndex++
    }
  }

  if (imagePaths.length === 0) {
    throw InfraError('No images were generated by Gemini', { stage: 'image:gemini' })
  }

  const processingTime = Date.now() - startTime
  const primaryPath = imagePaths[0] as string
  const primaryFile = Bun.file(primaryPath)
  const imageFileSize = primaryFile.size

  logGenCompleted('image', 'gemini', options.model, processingTime, imagePaths)

  const metadata: Step5Metadata = {
    imageService: 'gemini',
    imageModel: options.model,
    processingTime,
    imageCount: imagePaths.length,
    imageFileNames: imagePaths.map((imagePath) => basename(imagePath)),
    imageFileSize,
    imageWidth: undefined,
    imageHeight: undefined,
    requestMode: mode,
    ...(providerReturnedModel ? { providerReturnedModel } : {}),
    ...(groundingMetadata !== undefined ? { groundingMetadata } : {})
  }

  return { imagePaths, metadata }
}
