export const DEFAULT_CLI_CONCURRENCY = 7
export const DEFAULT_OCR_CONCURRENCY = 10
export const DEFAULT_TTS_CHUNK_CONCURRENCY = 30
export const DEFAULT_GROK_TTS_CHUNK_CONCURRENCY = 50
export const DEFAULT_ALL_PROVIDER_CONCURRENCY = 7

export const DEFAULT_CONCURRENCY_FLAG_VALUE = String(DEFAULT_CLI_CONCURRENCY)
export const DEFAULT_TTS_CHUNK_CONCURRENCY_FLAG_VALUE = String(DEFAULT_TTS_CHUNK_CONCURRENCY)
