import { ValidationError } from '~/utils/error-handler'
import { HOSTED_PROVIDER_ENV_CHECKS } from '../cli/commands/setup-and-utilities/setup/hosted-provider-config'

export const renderEnvironmentReference = (): string => `## Environment reference

The maintained hosted-provider registry contains ${HOSTED_PROVIDER_ENV_CHECKS.length} credentials. Empty, blank and shipped example placeholders are unconfigured. Credential observations never contain secret values; resolution trims valid values.

| Credential | Capabilities | Configuration selectors |
| --- | --- | --- |
${HOSTED_PROVIDER_ENV_CHECKS.map(provider => `| \`${provider.envVar}\` | ${provider.stages.join(', ')} | ${provider.configPaths.map(path => `\`${path}\``).join(', ') || 'Selected operation only'} |`).join('\n')}

Runtime controls include \`AUTOSHOW_PROJECT_ROOT\`, \`AUTOSHOW_SOURCE_IDENTITY_ROOT\`, \`AUTOSHOW_SOURCE_IDENTITY_ALIAS\`, \`AUTOSHOW_REQUIRED_IMAGE_MODEL\`, and \`AUTOSHOW_DISABLE_HTTP_KEEPALIVE\`. Internal setup handoffs use \`AUTOSHOW_SETUP_NO_ORPHANS_CHILD\` and \`AUTOSHOW_NETWORK_CHECK_CHILD_TIMEOUT_MS\`. Terminal color uses \`NO_COLOR\` and \`FORCE_COLOR\`; flags override these controls. These are separate from provider credentials.

Doctor is offline and advisory by default. Strict doctor rejects every warning about configuration, configured cookies, runtimes, local model assets or selected hosted defaults. Optional unselected credentials do not fail strict mode. Operation execution resolves credentials for its final selected providers, including URL, voice, comic and soundscape helpers. Catalog access is not proof of credit or generation admission.

Tests use exported values only, never a separate dotenv parser. Fixture mode is the default. Live registration requires \`AUTOSHOW_TEST_CREDENTIAL_MODE=live\` and valid JSON arrays in both \`AUTOSHOW_TEST_BUDGET_EVALUATED_KEYS\` and \`AUTOSHOW_TEST_BUDGET_SKIP_KEYS\`; every test key must have been evaluated. Missing or corrupt evidence cannot execute paid callbacks. Direct live tests require this same explicit evidence. \`bun run t:provider --budget ...\` selects live mode and generates budget evidence; set \`AUTOSHOW_TEST_CREDENTIAL_KEYS\` to a JSON array of the registered credential names needed by that selection. Only those exports reach workers, and only a live test's declared credentials reach its CLI children. An absent budget leaves paid tests unadmitted.

Docker launchers share one connection contract: \`PATH\`, \`HOME\`, \`DOCKER_HOST\`, \`DOCKER_CONTEXT\`, \`DOCKER_CONFIG\`, \`DOCKER_TLS_VERIFY\`, \`DOCKER_CERT_PATH\`, and \`XDG_RUNTIME_DIR\`. Provider credentials never reach the Docker client unless explicitly delivered to a container through Docker arguments or an env file.

Generated by \`src/tools/environment-reference.ts\`; edit the registry and generator, then regenerate this section.
`

export const ENVIRONMENT_REFERENCE_START = '<!-- environment-reference:start -->'
export const ENVIRONMENT_REFERENCE_END = '<!-- environment-reference:end -->'

export const updateEnvironmentReferenceSection = (document: string): string => {
  const start = document.indexOf(ENVIRONMENT_REFERENCE_START)
  const end = document.indexOf(ENVIRONMENT_REFERENCE_END)
  const section = `${ENVIRONMENT_REFERENCE_START}\n${renderEnvironmentReference()}${ENVIRONMENT_REFERENCE_END}`
  if (start === -1 && end === -1) return `${document.trimEnd()}\n\n${section}\n`
  if (start < 0 || end < start || document.indexOf(ENVIRONMENT_REFERENCE_START, start + 1) >= 0 || document.indexOf(ENVIRONMENT_REFERENCE_END, end + 1) >= 0) throw ValidationError('Consolidated report has invalid environment section markers.')
  return document.slice(0, start) + section + document.slice(end + ENVIRONMENT_REFERENCE_END.length)
}

if (import.meta.main) {
  const report = Bun.file(new URL('../docs/reports/high-priority-metareport-2026-09-11.md', import.meta.url))
  const document = await report.exists() ? await report.text() : '# High-priority implementation and consolidated report summary\n'
  await Bun.write(report, updateEnvironmentReferenceSection(document))
}
